### ISSUE TITLE
ESP resetting constantly when broker not reachable

### ISSUE THREAD

**Issue by 0xdefec71f** [hideakitai/MQTTPubSubClient#10]
Thank you for the lib, works good. 

But there is one issue: When the broker is not reachable, an ESP32 is resetting constantly (most likely WDT reset). You can easily test this whith your provided example code (no WebSocket, no ssl) and setting a wrong port, like e.g. 1884 (no broker there). 
Any advice? Why is it blocking instead of returning an error?

Best regards

**Comment by hideakitai** [comment]
Fixed by https://github.com/hideakitai/MQTTPubSubClient/pull/19
