### ISSUE TITLE
First connection over WebSocket always fails

### ISSUE THREAD

**Issue by jacand** [hideakitai/MQTTPubSubClient#17]
When connecting to the server using the arduinoWebSockets lib on ESP32, the first connection attempt always fails. I narrowed it down to the CONNACK message which turns out to be read as { 0 }, which causes a connection abort. The 0 is definitely not what the server sends. So I tracked it down to the following line which initializes the receive buffer queue to contain a single { 0 } (rather than the empqty queue {} ). This is what causes the first connection to always fail.

https://github.com/hideakitai/MQTTPubSubClient/blob/815a809dc89431aa26f2e6f041d277927f790df0/src/MQTTPubSubClient.h#L60C34-L60C48

Just change the buffer queue initializer from {0} to {} and everything works as it should.

(Sorry, I didn't want to go through the whole fork->commit->pull request hazzle to make this simple change.)

**Comment by hideakitai** [comment]
Fixed. Thank you so much!
