### ISSUE TITLE
Callback function not receive

### ISSUE THREAD

**Issue by fazerlab** [hideakitai/MQTTPubSubClient#25]
Hi, i tried the example in ESP32: 
```
#include <WiFi.h>
#include <WebSocketsClient.h>  // include before MQTTPubSubClient.h
#include <MQTTPubSubClient.h>  //https://github.com/hideakitai/MQTTPubSubClient

WebSocketsClient client;
MQTTPubSubClient mqtt;

void setup() {
    // start your network
    WiFi.begin("blabla", "blublu");
    // connect to host with MQTT over WebSocket securely
    client.beginSSL("public.cloud.shiftr.io", 443);
    client.setReconnectInterval(2000);
    // initialize mqtt client
    mqtt.begin(client);
    // connect to mqtt broker
    mqtt.connect("arduino", "public", "public");

    // subscribe callback which is called when every packet has come
    mqtt.subscribe([](const String& topic, const String& payload, const size_t size) {
        Serial.println("mqtt received: " + topic + " - " + payload);
    });
    // subscribe topic and callback which is called when /hello has come
    mqtt.subscribe("/paradise/paradise_msg", [](const String& payload, const size_t size) {
        Serial.print("msg:  ");
        Serial.println(payload);
    });
}

void loop() {
    // should be called to trigger callbacks
     mqtt.update();    
     // publish message
     static uint32_t prev_ms = millis();
     if (millis() > prev_ms + 1000) {
        prev_ms = millis();
        mqtt.publish("/paradise/paradise_msg", "world");
    }
}

```
and a HTML/Javascript client:
```
<html>

<head>
<title>Msg MQTT </title>
  <!-- https://github.com/mqttjs/MQTT.js -->
<script src="mqtt.min.js"></script>

<script>
  const options_shiftr = {
        clean: true, // retain session
        connectTimeout: 4000, // Timeout period
        // Authentication information
        clientId: 'arduino',
        username: 'public',
        password: 'public',
  }  
  const connectUrl = 'wss://public.cloud.shiftr.io:443'
  const client = mqtt.connect(connectUrl, options_shiftr)  
  
  client.subscribe("/paradise/paradise_msg")

  client.on("message", function (topic, payload) {    
    console.log ("Recv: " + payload.toString());    
  })

  client.on('connect', function () {
  console.log('connected ao broker')
})
  
</script>  
</body>

</html>
</head> 
```
This client receive all message send by ESP32, but ESP32 dont receive in callback.
I need help to solve this.
Thank you

**Comment by hideakitai** [comment]
Nothing appears to be sent from JS. What are you sending?

**Comment by fazerlab** [comment]
Hi. ESP32 sent and JS just receive.
Callback function in ESP32 should receive the message , right?

**Comment by hideakitai** [comment]
Yes

**Comment by fazerlab** [comment]
But don´t receive

**Comment by hideakitai** [comment]
？？？

> Hi. ESP32 sent and JS just receive.

You should send some message from us to esp32

**Comment by jpurvey** [comment]
I believe I am having a similar issue, see code below:

I am able to listen for messages coming from the ESP32 on my Home Assistant client, but anything I send to the "/Hello" subscription from HA does not show up on the ESP32 serial monitor. Not only that, but if I am understanding this correctly I should be seeing "/hello world" after each message publishing, right? Because the ESP32 is subscribed to those messages even if it is the one sending them.

Thanks for any guidance, some screenshots are below.

![image](https://github.com/hideakitai/MQTTPubSubClient/assets/62523653/37ead6e4-138e-4190-9345-8ee7168355a4)

![image](https://github.com/hideakitai/MQTTPubSubClient/assets/62523653/8d6c29d8-1e46-4a1e-a51a-c0164e5034c6)



#include <WiFi.h>
#include <MQTTPubSubClient.h>

const char* ssid = "OMICRON420";
const char* pass = "";

WiFiClient client;
MQTTPubSubClient mqtt;

void connect() {
connect_to_wifi:
    Serial.print("connecting to wifi...");
    while (WiFi.status() != WL_CONNECTED) {
        Serial.print(".");
        delay(1000);
    }
    Serial.println(" connected!");

connect_to_host:
    Serial.print("connecting to host...");
    client.stop();
    while (!client.connect("192.168.1.30", 1883)) {
        Serial.print(".");
        delay(1000);
        if (WiFi.status() != WL_CONNECTED) {
            Serial.println("WiFi disconnected");
            goto connect_to_wifi;
        }
    }
    Serial.println(" connected!");

    Serial.print("connecting to mqtt broker...");
    mqtt.disconnect();
    while (!mqtt.connect("arduino", "mqtt_user", "mqttpassword")) {
        Serial.print(".");
        delay(1000);
        if (WiFi.status() != WL_CONNECTED) {
            Serial.println("WiFi disconnected");
            goto connect_to_wifi;
        }
        if (client.connected() != 1) {
            Serial.println("WiFiClient disconnected");
            goto connect_to_host;
        }
    }
    Serial.println(" connected!");
}

void setup() {
    Serial.begin(115200);
    WiFi.begin(ssid, pass);

    // initialize mqtt client
    mqtt.begin(client);

    // subscribe callback which is called when every packet has come
    mqtt.subscribe([](const String& topic, const String& payload, const size_t size) {
        Serial.println("mqtt received: " + topic + " - " + payload);
    });

    // subscribe topic and callback which is called when /hello has come
    mqtt.subscribe("/hello", [](const String& payload, const size_t size) {
        Serial.print("/hello ");
        Serial.println(payload);
    });

    connect();
}

void loop() {
    mqtt.update();  // should be called

    if (!mqtt.isConnected()) {
        connect();
    }

    // publish message
    static uint32_t prev_ms = millis();
    if (millis() > prev_ms + 1000) {
        prev_ms = millis();
        mqtt.publish("/hello", "world");
    }
}

**Comment by hideakitai** [comment]
Does the example sketch work?

**Comment by fazerlab** [comment]
New experiment based in example WiFiMQTToverWebSocketSecure.ino and client HTML/JS

ESP32 code:

```
#include <WiFi.h>
#include <WebSocketsClient.h>  // include before MQTTPubSubClient.h
#include <MQTTPubSubClient.h>

const char* ssid = "blabla";
const char* pass = "blueblue";

WebSocketsClient client;
MQTTPubSubClient mqtt;

void connect() {
connect_to_wifi:
    Serial.print("connecting to wifi...");
    while (WiFi.status() != WL_CONNECTED) {
        Serial.print(".");
        delay(1000);
    }
    Serial.println(" connected!");

connect_to_host:
    Serial.println("connecting to host...");
    client.disconnect();
    client.beginSSL("public.cloud.shiftr.io", 443);    
    client.setReconnectInterval(2000);

    Serial.print("connecting to mqtt broker...");
    while (!mqtt.connect("arduino", "public", "public")) {
        Serial.print(".");
        delay(1000);
        if (WiFi.status() != WL_CONNECTED) {
            Serial.println("WiFi disconnected");
            goto connect_to_wifi;
        }
        if (!client.isConnected()) {
            Serial.println("WebSocketsClient disconnected");
            goto connect_to_host;
        }
    }
    Serial.println(" connected!");
}

void setup() {
    Serial.begin(115200);
    WiFi.begin(ssid, pass);

    // initialize mqtt client
    mqtt.begin(client);

    // subscribe callback which is called when every packet has come
    mqtt.subscribe([](const String& topic, const String& payload, const size_t size) {
        Serial.println("mqtt received: " + topic + " - " + payload);
    });

    // subscribe topic and callback which is called when /hello has come
    mqtt.subscribe("/paradise/paradise_msg", [](const String& payload, const size_t size) {
        Serial.print("recv:  ");
        Serial.println(payload);
    });

    connect();
}

void loop() {
    mqtt.update();  // should be called

    if (!mqtt.isConnected()) {
        connect();
    }

    
}
```
Client HTML/JS

```
<html>

<head>
<title>Msg MQTT v1</title>
  <!-- https://github.com/mqttjs/MQTT.js -->
<script src="mqtt.min.js"></script>

<script>
  const options_shiftr = {
        clean: true, // retain session
        connectTimeout: 4000, // Timeout period
        // Authentication information
        clientId: 'arduino',
        username: 'public',
        password: 'public',
  }  
  const connectUrl = 'wss://public.cloud.shiftr.io:443'
  const client = mqtt.connect(connectUrl, options_shiftr)  
  
  client.subscribe("/paradise/paradise_msg")

  // callback message received
  client.on("message", function (topic, payload) {    
    console.log ("Recv: " + payload.toString());    
  })

  client.on('connect', function () {
  console.log('connected ao broker')
})

  // send message every 2 second
  setInterval(function () {
                            client.publish("/paradise/paradise_msg", "Hello mqtt");
                           }, 3000);
  
  
</script>  
</body>

```
Result: 

![image](https://github.com/hideakitai/MQTTPubSubClient/assets/42142127/c413c3d7-75c8-47ef-a892-ed6237d78dca)

Conclusion:
ESP32 connect to wifi and broker, but don´t receive message

**Comment by hideakitai** [comment]
To help us isolate the problem, please try the following steps.

1. Can the example publish and subscribe to the message /hello “as is”?
2. Can your js code subscribe to the message /hello published by your device (as same as 1)?
3. Remove publishing /hello on your device and add publishing /hello from your js code. Can the device and your js code subscribe /hello as before?
4. Replace /hello to your message. Can the device and your js code subscribe to your message?

**Comment by fazerlab** [comment]
To help us isolate the problem, please try the following steps.

Can the example publish and subscribe to the message /hello “as is”?
Device just publish 

Can your js code subscribe to the message /hello published by your device (as same as 1)?
yes work fine

Remove publishing /hello on your device and add publishing /hello from your js code. Can the device and your js code subscribe /hello as before?
Device don´t receive(subscribe) , JS client receive (subscribe) 

Replace /hello to your message. Can the device and your js code subscribe to your message?
Device no, client JS work as expected

Conclusion
Subscribe on Device ESP32 don´t work

Video demo: 
https://youtu.be/lpCVfJUjCBI

**Comment by hideakitai** [comment]
Thanks, I will try later (currently, I don't have any devices)

**Comment by fazerlab** [comment]
Thanks

**Comment by hideakitai** [comment]
The problem was just an order of `connect()` and `subscribe()` order. See https://github.com/hideakitai/MQTTPubSubClient/pull/27 for details.

**Comment by fazerlab** [comment]
Thank you. Work fine!!!
