### ISSUE TITLE
WiFiMQTTSecureAWS example  is not compiling for MKR1010

### ISSUE THREAD

**Issue by kathesama** [hideakitai/MQTTPubSubClient#3]
Example WiFiMQTTSecureAWS is getting this error: **Compilation error: Error: 2 UNKNOWN: exit status 1**

I'm not pretty sure but I think could be WiFiClientSecure library, I couldn't find at Library Manager on arduino manager for IDE 2.0.0-beta.11. 

I read that WiFiClientSecure is for ESP devices, so I'm not sure... 

Could you confirm please?

I'm using a MKR1010 device

**Comment by hideakitai** [comment]
@kathesama Hi, thank you for reporting.
First, this library does not support IDE 2.0 yet, so could you try the example in IDE 1.8.16?

As you know, the examples are made only for ESP series, so you need to change the WiFi initialization codes before line 59 depending on your platform (WiFiNINA, WiFi101, etc.).

https://github.com/hideakitai/MQTTPubSubClient/blob/eb98df3e6e499973ac7c51d51ddfe6c99b292685/examples/WiFiMQTTSecureAWS/WiFiMQTTSecureAWS.ino#L59

I'm not familiar with the secure clients of WiFININA and other WiFi libraries, so I'm so happy to let me know how to use them to connect securely!

**Comment by hideakitai** [comment]
I'm closing this issue, but please feel free to reopen it if you still have problems.
