### ISSUE TITLE
connect to server max retries times

### ISSUE THREAD

**Issue by majianming21** [hideakitai/MQTTPubSubClient#30]
when i  call `mqttClient.connect` method to connect server ,some case about network or server error
but it always block in this code
```c++
#ifdef MQTTPUBSUBCLIENT_USE_WEBSOCKETS
            while (!client->isConnected()) {
                client->loop();
                delay(10);
            }
#endif
```
i want to some times can return caller for try other solution,may i get some suggestion

**Comment by hideakitai** [comment]
Have you tried the example sketch as is?

**Comment by majianming21** [comment]
i try use  WiFiMQTToverWebSocket.ino example,but stil made.

**Comment by majianming21** [comment]
you can test it for some server error as no auth or internal error

**Comment by majianming21** [comment]
i test it work
```
        bool connect(const String& client_id, const String& user = "", const String& pass = "",const int retries=100) {
            if (this->isConnected()) {
                this->close();
            }

#ifdef MQTTPUBSUBCLIENT_USE_WEBSOCKETS
            int leftRetries=retries;
            while (!client->isConnected() && leftRetries-->0) {
                client->loop();
                delay(10);
            }
            if (!client->isConnected()){
                return false;
            }
#endif
...

```
i want to caller know it connect failed.

**Comment by hideakitai** [comment]
OK, you need a connection timeout. It's a good point.

**Comment by hideakitai** [comment]
You can use timeout from v0.3.1. Please set timeout by `setTimeout()` method.

https://github.com/hideakitai/MQTTPubSubClient/pull/31

**Comment by majianming21** [comment]
i test  v0.3.1 in my code ,is fine
