### ISSUE TITLE
Unable to receive message from Websockets MQTT

### ISSUE THREAD

**Issue by ravirxeddy** [hideakitai/MQTTPubSubClient#35]
This is the code I am using 

```cpp
#include <WiFi.h>
#include <WebSocketsClient.h>  // include before MQTTPubSubClient.h
#include <MQTTPubSubClient.h>

const char* ssid = "Ravi iPhone";
const char* pass = "xxxxxxx";

WebSocketsClient client;
MQTTPubSubClient mqtt;

void connect() {
connect_to_wifi:
    Serial.print("connecting to wifi...");
    while (WiFi.status() != WL_CONNECTED) {
        Serial.print(".");
        delay(1000);
    }
    Serial.println(" connected!");

connect_to_host:
    Serial.println("connecting to host...");
    client.disconnect();
    client.beginSSL("axkvj8kbcq.cricheroes.in", 8884);
    // client.beginSSL("test.mosquitto.org", 8081, "/", "", "mqtt");  // "mqtt" is required
    client.setReconnectInterval(2000);

    Serial.print("connecting to mqtt broker...");
    while (!mqtt.connect("CHW-113_1718789743248", "", "")) {
        Serial.print(".");
        delay(1000);
        if (WiFi.status() != WL_CONNECTED) {
            Serial.println("WiFi disconnected");
            goto connect_to_wifi;
        }
        if (!client.isConnected()) {
            Serial.println("WebSocketsClient disconnected");
            goto connect_to_host;
        }
    }
    Serial.println(" connected!");
}

void setup() {
    Serial.begin(115200);
    WiFi.begin(ssid, pass);

    // initialize mqtt client
    mqtt.begin(client);

    // connect to wifi, host and mqtt broker
    connect();

    // subscribe callback which is called when every packet has come
    mqtt.subscribe([](const String& topic, const String& payload, const size_t size) {
        Serial.println("mqtt received: " + topic + " - " + payload);
    });

    // subscribe topic and callback which is called when /hello has come
    mqtt.subscribe("scorecard-11737721", [](const String& payload, const size_t size) {
        Serial.print("/hello ");
        Serial.println(payload);
    });
}

void loop() {
    mqtt.update();  // should be called

    if (!mqtt.isConnected()) {
        connect();
    }

    // publish message
    static uint32_t prev_ms = millis();
    if (millis() > prev_ms + 1000) {
        prev_ms = millis();
        mqtt.publish("/hello", "world");
    }
}
```

WebSockets/MQTT Server : axkvj8kbcq.cricheroes.in
Port : 8884
SSL : yes
Topic: scorecard-11737721
Client: CHW-113_1718789743248
(CHW-some-random-number-below-1000-timestamp)

The same WebSockets/MQTT with HTML is working 

<html>

<head>
<title>Msg MQTT </title>
  
<script src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script>

<script>
  const options_shiftr = {
        clean: true, // retain session
        connectTimeout: 4000, // Timeout period
        // Authentication information
        clientId: 'CHW-478_1718772581705',
        username: '',
        password: '',
  }  
  const connectUrl = 'wss://axkvj8kbcq.cricheroes.in:8884'
  const client = mqtt.connect(connectUrl, options_shiftr)  
  
  client.subscribe("scorecard-11737721")

  client.on("message", function (topic, payload) {    
    console.log ("Recv: " + payload.toString());    
  })

  client.on('connect', function () {
  console.log('connected ao broker')
})
  
</script>  
</body>

</html>
</head> 

But with ESP32 it is not getting any message. 

Please help.

**Comment by ravirxeddy** [comment]
`<html>

<head>
<title>Msg MQTT </title>
  
<script src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script>

<script>
  const options_shiftr = {
        clean: true, // retain session
        connectTimeout: 4000, // Timeout period
        // Authentication information
        clientId: 'CHW-478_1718772581705',
        username: '',
        password: '',
  }  
  const connectUrl = 'wss://axkvj8kbcq.cricheroes.in:8884'
  const client = mqtt.connect(connectUrl, options_shiftr)  
  
  client.subscribe("scorecard-11737721")

  client.on("message", function (topic, payload) {    
    console.log ("Recv: " + payload.toString());    
  })

  client.on('connect', function () {
  console.log('connected ao broker')
})
  
</script>  
</body>

</html>
</head> `

**Comment by ravirxeddy** [comment]
`<html>

<head>
<title>Msg MQTT </title>
  
<script src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script>

<script>
  const options_shiftr = {
        clean: true, // retain session
        connectTimeout: 4000, // Timeout period
        // Authentication information
        clientId: 'CHW-478_1718772581705',
        username: '',
        password: '',
  }  
  const connectUrl = 'wss://axkvj8kbcq.cricheroes.in:8884'
  const client = mqtt.connect(connectUrl, options_shiftr)  
  
  client.subscribe("scorecard-11737721")

  client.on("message", function (topic, payload) {    
    console.log ("Recv: " + payload.toString());    
  })

  client.on('connect', function () {
  console.log('connected ao broker')
})
  
</script>  
</body>

</html>
</head> `

**Comment by hideakitai** [comment]
First, please format your code because I can't read the code.

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

You subscribe to the topic `scorecard-11737721`, 

```cpp
    mqtt.subscribe("scorecard-11737721", [](const String& payload, const size_t size) {
```

but you publish the topic `/hello`.

```cpp
        mqtt.publish("/hello", "world");
```

Where has the topic `scorecard-11737721` been published? First, please confirm if the topic `/hello` can be subscribed.

**Comment by ravirxeddy** [comment]
```javascript
<html>

<head>
<title>Msg MQTT </title>
  <!-- https://github.com/mqttjs/MQTT.js -->
<script src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script>

<script>
  const options_shiftr = {
        clean: true, // retain session
        connectTimeout: 4000, // Timeout period
        // Authentication information
        // Cline code is (CHW-some-random-number-below-1000-timestamp)
        clientId: 'CHW-478_1718772581705',
        username: '',
        password: '',
  }  
  const connectUrl = 'wss://axkvj8kbcq.cricheroes.in:8884'
  const client = mqtt.connect(connectUrl, options_shiftr)  
  // Score card https://cricheroes.com/live-matches , click on match and from utl get the value
  client.subscribe("scorecard-11737721")

  client.on("message", function (topic, payload) {    
    console.log ("Recv: " + payload.toString());    
  })

  client.on('connect', function () {
  console.log('connected ao broker')
})
  
</script>  
</body>

</html>
</head> 
```

**Comment by ravirxeddy** [comment]
In my actual code I have commented out the line , 
 mqtt.publish("/hello", "world");

The public to /hello is working if I have this code

 mqtt.subscribe("/hello", [](const String& payload, const size_t size) {

But actual message from the topic , scorecard-11737721 I am not getting.

**Comment by hideakitai** [comment]
> The public to /hello is working if I have this code

Does sending /hello from your JS work?

**Comment by hideakitai** [comment]
Also, does publish/subscribe /hello both on Arduino with your broker work?

**Comment by ravirxeddy** [comment]
> Also, does publish/subscribe /hello both on Arduino with your broker work?

19:46:35.521 -> /hello world
19:46:36.519 -> mqtt received: /hello - world

This is working fine from ESP32. 

Also the broker is not owned by me. I am trying to build a electronic score board for local matches based on the site https://cricheroes.com/live-matches

**Comment by ravirxeddy** [comment]
Just for you to know, data comes as json of size around 15KB. Is the size is a problem here?

**Comment by ravirxeddy** [comment]
"After making this change, I have been receiving messages."
MQTTPubSub::PubSubClient<25006> mqtt;

**Comment by hideakitai** [comment]
I am glad it worked. Please reopen this issue of you still need help.
