### ISSUE TITLE
When WebSocketsClient disconnected, subscribe doesn't work 

### ISSUE THREAD

**Issue by kibu7** [hideakitai/MQTTPubSubClient#38]
Hi,
if the ESP lost Wifi and reconnects the ESP can publish messages but can't receive any more messages. I used [this](https://github.com/hideakitai/MQTTPubSubClient/blob/main/examples/WiFiMQTToverWebSocket/WiFiMQTToverWebSocket.ino) example. Do I need to resubscribe to the topic?

Thanks for you help
kibu

**Comment by hideakitai** [comment]
Hi @kibu7 

I haven't tested it yet, but you may be right. Could you re-subscribe after disconnection? Or have you resolved by re-subscribing?

**Comment by hideakitai** [comment]
If you still need help, please reopen this issue.
