### ISSUE TITLE
Can subscribe to 16 topics max

### ISSUE THREAD

**Issue by sven1729** [hideakitai/MQTTPubSubClient#4]
I am running this library on an Arduino Mega.
I am subscribing to more than 16 topics. 
`mqtt.subscribe()` returns true and the broker also logs a successful subscription.
At runtime only the most recently subscribed 16 topics' callbacks get called. The earlier ones are never called when a message is published on their topic.

Is there a parameter to increase this number or another way around this limitation?
Many thanks already.

**Comment by sven1729** [comment]
I found that editing `src/MQTTPubSubClient/util/ArxContainer/ArxContainer.h` and changing 

```c
#ifndef ARX_VECTOR_DEFAULT_SIZE
#define ARX_VECTOR_DEFAULT_SIZE 32
#endif  // ARX_VECTOR_DEFAULT_SIZE

#ifndef ARX_DEQUE_DEFAULT_SIZE
#define ARX_DEQUE_DEFAULT_SIZE 32
#endif  // ARX_DEQUE_DEFAULT_SIZE

#ifndef ARX_MAP_DEFAULT_SIZE
#define ARX_MAP_DEFAULT_SIZE 32
#endif  // ARX_MAP_DEFAULT_SIZE
```

increases this limit. But seems to cause crashes.  Is this plausible and what would be the correct way to do this?

**Comment by hideakitai** [comment]
@sven1729 Sorry for the late reply. I've added the configuration to change the callback size. Please use it like:

```cpp
MQTTPubSub::PubSubClient<128, 32> mqtt;
```
Please let me know (and reopen this issue)  if you still have a problem.
