### ISSUE TITLE
invalid conversion from 'const char*' to 'const uint8_t*'

### ISSUE THREAD

**Issue by kibu7** [hideakitai/MQTTPubSubClient#8]
hi, I'm getting an error if im using the line: "client.beginSSL("test.mosquitto.org", 8081, "/", "", "mqtt");  // "mqtt" is required"
the only thing I changed is the <WiFi.h> to <ESP8266WiFi.h> because Im using the Esp8266.

Full error message:
iFiMQTToverWebSocketSecure:25:54: error: invalid conversion from 'const char*' to 'const uint8_t*' {aka 'const unsigned char*'} [-fpermissive]
   25 |     client.beginSSL("test.mosquitto.org", 8081, "/", "", "mqtt");  // "mqtt" is required
      |                                                      ^~
      |                                                      |
      |                                                      const char*
In file included from /var/folders/68/7cs7wbjs5q7fqkmhjydst3v00000gn/T/arduino_modified_sketch_324362/WiFiMQTToverWebSocketSecure.ino:3:
/Users/I545488/Documents/Arduino/libraries/arduinoWebSockets/src/WebSocketsClient.h:50:93: note:   initializing argument 4 of 'void WebSocketsClient::beginSSL(const char*, uint16_t, const char*, const uint8_t*, const char*)'
   50 |     void beginSSL(const char * host, uint16_t port, const char * url = "/", const uint8_t * fingerprint = NULL, const char * protocol = "arduino");
      |                                                                                             ^
exit status 1
invalid conversion from 'const char*' to 'const uint8_t*' {aka 'const unsigned char*'} [-fpermissive]

**Comment by hideakitai** [comment]
As the error message says, “invalid conversion from 'const char*' to 'const uint8_t*' {aka 'const unsigned char*'}. Please use uint8_t* or cast to it.
